package Presentacion;

import bo.edu.uagrm.ficct.inf310sb.grafos.excepciones.ExcepcionAristaNoExiste;
import bo.edu.uagrm.ficct.inf310sb.grafos.excepciones.ExcepcionAristaYaExiste;
import bo.edu.uagrm.ficct.inf310sb.grafos.pesados.GrafoPesado;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MainGrafos extends javax.swing.JFrame {

    private String accion;
    private GrafoPesado grafo;
    private int ciudadOrigen, ciudadDestino;
    private int VR[];

    public MainGrafos() {
        initComponents();
        grafo = new GrafoPesado();
        deshabilitarHabilitar(false);
        cbOrigen.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String ciudadSeleccionadaAurita = e.getItem().toString();
                    ciudadOrigen = cbOrigen.getSelectedIndex();
                    if (ciudadOrigen == ciudadDestino) {
                        accion = "ERROR";
                    } else {
                        accion = "confirmarRuta";
                    }
                }
            }
        });
        cbDestino.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String ciudadSeleccionadaAurita = e.getItem().toString();
                    //ciudadDestino = ciudadSeleccionadaAurita;
                    ciudadDestino = cbDestino.getSelectedIndex();
//                    if (ciudadSeleccionadaAurita.equals(ciudadOrigen)) {
                    if (ciudadDestino == ciudadOrigen) {
                        accion = "ERROR";
                    } else {
                        accion = "confirmarRuta";
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDibujo = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbOrigen = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        areaDibujo2 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GrafoPesado");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        areaDibujo.setBackground(new java.awt.Color(204, 204, 204));
        areaDibujo.setPreferredSize(new java.awt.Dimension(550, 350));
        areaDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaDibujoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout areaDibujoLayout = new javax.swing.GroupLayout(areaDibujo);
        areaDibujo.setLayout(areaDibujoLayout);
        areaDibujoLayout.setHorizontalGroup(
            areaDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        areaDibujoLayout.setVerticalGroup(
            areaDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jButton1.setText("AÑADIR CIUDAD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("AÑADIR RUTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbOrigen.setEnabled(false);

        cbDestino.setEnabled(false);

        jLabel1.setText("CIUDAD ORIGEN");

        jLabel2.setText("CIUDAD DESTINO");

        jLabel3.setText("PRECIO (Bs)");

        jtPrecio.setEnabled(false);

        jButton3.setText("GUARDAR RUTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CALCULAR RUTAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CAMINO CON MENOR COSTO");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("MOSTRAR"); // NOI18N
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        areaDibujo2.setPreferredSize(new java.awt.Dimension(550, 350));

        javax.swing.GroupLayout areaDibujo2Layout = new javax.swing.GroupLayout(areaDibujo2);
        areaDibujo2.setLayout(areaDibujo2Layout);
        areaDibujo2Layout.setHorizontalGroup(
            areaDibujo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        areaDibujo2Layout.setVerticalGroup(
            areaDibujo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel6.setText("Su ruta mas corta del Grafo Pesado aparecerá aquí");

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel7.setText("Añada su ciudad aquí ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(areaDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(areaDibujo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addGap(307, 307, 307)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(areaDibujo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(areaDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaDibujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaDibujoMouseClicked
        // CUANDO HAGA CLICK EN EL AREA DE DIBUJO
        if (accion.equals("nuevaCiudad")) {
            String nuevoNombreDeCiudad = input("Introducir nombre de Ciudad");
            if (!existeCiudadConEseNombre(nuevoNombreDeCiudad)) {
                if (nuevoNombreDeCiudad.length() > 0) {
                    int posX = evt.getX(), posY = evt.getY();
                    grafo.addVertice(nuevoNombreDeCiudad, posX, posY);
                    cbDestino.addItem(nuevoNombreDeCiudad);
                    cbOrigen.addItem(nuevoNombreDeCiudad);
                    actualizarVista();
                } else {
                    show("Debe insertar un nombre");
                }
            } else {
                show("Ciudad ya Existe!");
            }
        }
        accion = "nada";
    }//GEN-LAST:event_areaDibujoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // espera el click en el area de dibujo
        accion = "nuevaCiudad";
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // AÑADIR RUTA 
        if (grafo.cantidadDeVertices() <= 1) {
            show("No hay suficientes ciudades");
        } else {
            deshabilitarHabilitar(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (accion.equals("confirmarRuta")) {
            int U = ciudadOrigen;
            int V = ciudadDestino;
            //double kilometrosDeLaRuta = 0;
            double PrecioDeLaRuta = 0;
            //try {       
                PrecioDeLaRuta = Double.parseDouble(jtPrecio.getText());
                if (U == -1 || V == -1) {
                    show("Ups!");
                } else {  
//                    if (!existeMismaRutaConCostoDiferente(kilometrosDeLaRuta) || !existeMismaRutaConPrecioDiferente(PrecioDeLaRuta)) {
                      if (!existeMismaRutaConPrecioDiferente(PrecioDeLaRuta)) {
                        try {                           
                            grafo.insertarArista(U, V, PrecioDeLaRuta);
                        } catch (ExcepcionAristaYaExiste ex) {                         
                        }
                        deshabilitarHabilitar(false);                     
                        actualizarVista();
                        
                    } else {
                        show("Ya existe una ruta entre estas ciudades");
                    }
                   
                }
//            } catch (Exception e) {
//                show("Precio o kilometro Invalido! ");
//            }
        } else {
            show("Las Ciudades deben ser diferentes! ");
            accion = "nada";

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // carga las matrices y realiza el algoritmo de floyd
        grafo.caragarM1();
        grafo.floyd1();
        jButton5.setEnabled(true);
      //  jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cbOrigen.setEnabled(true);
        cbDestino.setEnabled(true);
        jButton7.setEnabled(true);


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int U = ciudadOrigen;
        int V = ciudadDestino;
        try {
            if (grafo.existeCamino(U, V)) {
                cbOrigen.setEnabled(false);
                cbDestino.setEnabled(false);
                jButton7.setEnabled(false);
                
                List<Integer> aux = grafo.caminoMasCortoFloydWarshall(U, V);
                VR = new int[aux.size()];
                for (int i = 0; i < aux.size(); i++) {
                    VR[i] = aux.get(i);
                }
                mostrarRuta();
            } else {
                show("No se puede llegar");
                cbOrigen.setEnabled(false);
                cbDestino.setEnabled(false);
                jButton7.setEnabled(false);
            }
        } catch (ExcepcionAristaNoExiste ex) {
            
        }

    }//GEN-LAST:event_jButton7ActionPerformed
    //--------FUNCIONES Y PROCEDIMIENTOS PARA VALIDAR---
    private boolean existeMismaRutaConCostoDiferente(double kilometros) {
        int posicionDeCiudadOrigen = ciudadOrigen;
        int posicionDeCiudadDestino = ciudadDestino;
        if (grafo.existeAdyacencia(posicionDeCiudadOrigen,posicionDeCiudadDestino)) {
            for (int i = 0; i < grafo.listaDeAyacencia().get(posicionDeCiudadOrigen).size(); i++) {
                if (grafo.listaDeAyacencia().get(i).get(posicionDeCiudadOrigen).getPeso() == kilometros) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean existeMismaRutaConPrecioDiferente(double Precio) {
        int posicionDeCiudadOrigen = ciudadOrigen;
        int posicionDeCiudadDestino = ciudadDestino;
        if (grafo.existeAdyacencia(posicionDeCiudadOrigen,posicionDeCiudadDestino)) {
            for (int i = 0; i < grafo.listaDeAyacencia().get(posicionDeCiudadOrigen).size(); i++) {
                if (grafo.listaDeAyacencia().get(i).get(posicionDeCiudadOrigen).getPeso() == Precio) {
                    return true;
                }
            }
        }
        return false;
    }
    //--------FUNCIONES Y PROCEDIMIENTOS AUXILIARES ---

    private void show(String mensaje) {
        //MOSTRAR UN MENSAJE
        JOptionPane.showMessageDialog(rootPane, mensaje);
    }

    private String input(String mensaje) {
        //DESPLEGA UN IMPUT BOX
        return JOptionPane.showInputDialog(rootPane, mensaje, "");
    }

    private boolean existeCiudadConEseNombre(String nombreAVerificar) {
        for (String nombre : grafo.nombres) {
            if (nombre != null) {
                if (nombre.equals(nombreAVerificar)) {
                    return true;
                }
            }
        }
        return false;
    }

    private void deshabilitarHabilitar(boolean b) {
        //DESABILITAR O HABILITAR 
        cbOrigen.setEnabled(b);
        cbDestino.setEnabled(b);
        jtPrecio.setEnabled(b);
       // jtDistancia.setEnabled(b);
    }

    //---------FUNCIONES Y PROCEDIMIENTOS PARA GRAFICAR
    private void actualizarVista() {
        Graphics grafico = areaDibujo.getGraphics();
        grafico.setColor(Color.WHITE);
        grafico.fillRect(0, 0, areaDibujo.getWidth(), areaDibujo.getHeight());
        grafico.setColor(Color.BLACK);
        int ancho = 70;
        for (int i = 0; i < grafo.cantidadDeVertices(); i++) {
            grafico.drawOval(grafo.puntosX.get(i) - ancho / 2, grafo.puntosY.get(i) - ancho / 2, ancho, ancho);
            grafico.drawString(
                    grafo.nombres.get(i),
                    grafo.puntosX.get(i) - ancho / 2 + 5 * ((12 - grafo.nombres.get(i).length()) / 2),
                    grafo.puntosY.get(i) + 5
            );
            for (int j = 0; j < grafo.listaDeAyacencia().get(i).size(); j++) {
                int elemento = j;
                grafico.drawLine(
                        grafo.puntosX.get(i),
                        grafo.puntosY.get(i),
                        grafo.puntosX.get(grafo.listaDeAyacencia().get(i).get(j).getIndiceVertice()),
                        grafo.puntosY.get(grafo.listaDeAyacencia().get(i).get(j).getIndiceVertice())
                );
                grafico.drawString(
                        Double.toString(grafo.listaDeAyacencia().get(i).get(elemento).getPeso()) + " bs ",                        
                        (grafo.puntosX.get(i) + grafo.puntosX.get(grafo.listaDeAyacencia().get(i).get(j).getIndiceVertice())) / 2,
                        (grafo.puntosY.get(i) + grafo.puntosY.get(grafo.listaDeAyacencia().get(i).get(j).getIndiceVertice())) / 2
                );

            }
        }
    }

    private void mostrarRuta() {
        Graphics grafico = areaDibujo2.getGraphics();
        grafico.setColor(Color.WHITE);
        grafico.fillRect(0, 0, areaDibujo2.getWidth(), areaDibujo2.getHeight());
        grafico.setColor(Color.BLACK);
        int ancho = 70;
        for (int c = 0; c < VR.length; c++) {         
            int i = VR[c];
            grafico.drawOval(grafo.puntosX.get(i) - ancho / 2, grafo.puntosY.get(i) - ancho / 2, ancho, ancho);
            grafico.drawString(
                    grafo.nombres.get(i),
                    grafo.puntosX.get(i) - ancho / 2 + 5 * ((12 - grafo.nombres.get(i).length()) / 2),
                    grafo.puntosY.get(i) + 5
            );

            if (c < VR.length - 1) {
                int j = VR[c + 1];
                System.err.println("j: "+ j);
                grafico.drawLine(
                        grafo.puntosX.get(i),
                        grafo.puntosY.get(i),
                        grafo.puntosX.get(j),
                        grafo.puntosY.get(j)
                );
                grafico.drawString(
                        Double.toString(grafo.getPeso(i, j)) + " bs ",
                        (grafo.puntosX.get(i) + grafo.puntosX.get(j)) / 2,
                        (grafo.puntosY.get(i) + grafo.puntosY.get(j)) / 2
                );
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGrafos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel areaDibujo;
    private java.awt.Panel areaDibujo2;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbOrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtPrecio;
    // End of variables declaration//GEN-END:variables
}
